app:
  name: svc
  image:
    repository: "onecx/onecx-parameter-svc"
  db:
    enabled: true
  operator:
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-tn:read ]
    microservice:
      spec:
        description: OneCX Parameter Backend Service
        name: OneCX Parameter SVC
