---
openapi: 3.0.3
info:
  title: onecx-parameter data import
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /import/parameter:
    post:
      security:
        - oauth2: [ ocx-pa:write ]
      operationId: importParameter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataImport'
      responses:
        200:
          description: ok
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-pa:write: Grants write access
  schemas:
    DataImport:
      type: object
      properties:
        default:
          type: string
      additionalProperties:
        $ref: '#/components/schemas/DataImportApp'
    DataImportApp:
      type: object
      properties:
        default:
          type: string
      additionalProperties:
        $ref: '#/components/schemas/DataImportParam'
    DataImportParam:
      type: object
      properties:
        description:
          type: string
        name:
          type: string
        value:
          type: string
